"""create categories table

Revision ID: 1c8f71ad0e03
Revises: 2f138bcbee5d
Create Date: 2025-05-02 17:10:12.979632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8f71ad0e03'
down_revision: Union[str, None] = '2f138bcbee5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_major_name', sa.String(length=30), nullable=False),
    sa.Column('category_sub_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['category_id'], ondelete='CASCADE')
    op.drop_column('items', 'category_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_column('items', 'category_id')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
