"""add notification field with nullable true

Revision ID: 2ead9f3f6683
Revises: f81a9fbb499e
Create Date: 2025-04-30 10:54:54.030428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ead9f3f6683'
down_revision: Union[str, None] = 'f81a9fbb499e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification')
    # ### end Alembic commands ###
